### ISSUE TITLE
Remove redundant whitespace when aligning

### ISSUE THREAD

**Issue by farzadmf** [cpmcgrath/codealignment#52] opened 2016-10-23 17:12 UTC
First of all, AMAZING plugin! I use it EVERY MINUTE in Visual Studio

I have used [Vim Easy Align](https://github.com/junegunn/vim-easy-align), and one feature that I really liked about it is that it removes redundant white space, for example, these lines:

```
private readonly Dictionary<int, Item> _items             = new Dictionary<int, Item>();
private readonly Dictionary<int, Item> _hotKeyItems    = new Dictionary<int, Item>();
private readonly List<GameObject     > _slots        = new List<GameObject>();
private readonly List<GameObject     > _hotKeySlots      = new List<GameObject>();
```

become like this after aligning by the equal sign (`=`):

```
private readonly Dictionary<int, Item> _items       = new Dictionary<int, Item>();
private readonly Dictionary<int, Item> _hotKeyItems = new Dictionary<int, Item>();
private readonly List<GameObject     > _slots       = new List<GameObject>();
private readonly List<GameObject     > _hotKeySlots = new List<GameObject>();
```

However, in Visual Studio, if I align, they become like this:

```
private readonly Dictionary<int, Item> _items             = new Dictionary<int, Item>();
private readonly Dictionary<int, Item> _hotKeyItems       = new Dictionary<int, Item>();
private readonly List<GameObject     > _slots             = new List<GameObject>();
private readonly List<GameObject     > _hotKeySlots       = new List<GameObject>();
```

meaning that it always considers the rightmost character to be aligned with (here, equal sign `=`). I'm not sure if it's an easy thing to implement, but this is the ONLY feature I miss in this great Visual Studio plugin

**Comment by cpmcgrath** [comment] 2016-10-23 21:55
Hi, thanks for the kind words. I've had a ticket for this a while. I still haven't got around to doing something for it. 
I'm not sure if I want the solution to  just be "Automatically delete redundant white space" - there could be reasons why you want that white space there. My current thinking is a shortcut which removes all excess whitespace from the either the entire line or the next set of whitespace.
So in you example you'd do it with three operations - remove redundant whitespace, align by >, align by equals.

This would keep the operation very deliberate which is one of my tenets of Code Alignment.

The issue this is a duplicate of is #12

**Closed as completed by cpmcgrath** 2016-10-23 21:55 UTC
Labels: duplicate, enhancement, rejected

**Comment by farzadmf** [comment] 2016-10-24 21:30
Unfortunately, It seems that the issue you referenced has been open for more than 4 years! Do you plan on doing something for it in near future?
